services:
  redis:
    image: redis:8.2-rc1-alpine
    container_name: rediguard-redis-stack
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-stack-data:/data
    environment:
      - REDIS_ARGS=--save 60 1000 --appendonly yes
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
  redisinsights:
    image: redislabs/redisinsight:latest
    container_name: rediguard-redisinsights
    restart: unless-stopped
    ports:
      - "5540:5540"  # RedisInsight

volumes:
  redis-stack-data:
    driver: local
