services:
  redis:
    image: redis:8.2-rc1-alpine
    container_name: redisense-redis-stack
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-stack-data:/data
    environment:
      - REDIS_ARGS=--save 60 1000 --appendonly yes
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    network_mode: "host"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: rediscover-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - ENVIRONMENT=production
    depends_on:
      redis:
        condition: service_healthy
    network_mode: "host"


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: rediscover-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend
    network_mode: "host"

volumes:
  redis-stack-data:
    driver: local
